# Environments variables set foor all   `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="rust_web_app=debug"

## -- Secrets
SERVICE_DB_URL = "postgres://app_user:dev_only_pwd@ocalhost/app_db"


# This will be relative to Cargo.toml
# In deployed magess, probably use absolute path.
SERVICE_WEB_FOLDER="web-folder/" 